name: OpenAPI

on:
  workflow_dispatch:

permissions: read-all

jobs:
  generate-library:
    name: Generate API client library
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Generate client libraries
        run: yarn run generate-client

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: biip-tools-client
          path: generated-sources/biip-tools-client

  publish-library:
    name: Publish API client library
    runs-on: ubuntu-latest
    needs: [generate-library]
    permissions:
      packages: write
    steps:
      - name: Download client
        uses: actions/download-artifact@v3
        with:
          name: biip-tools-client

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org

      - name: Publish client library
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
